# Generated by Django 5.0.7 on 2024-11-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_teamproject_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamproject",
            name="summary_prompt_model",
            field=models.CharField(
                choices=[
                    ("mixtral_7bx8", "Mixtral 7bx8 (Default)"),
                    ("mixtral_22bx8", "Mixtral 22bx8"),
                    ("llama3_70b", "Llama 3.1 70b"),
                ],
                help_text="This AI summarization model is used if selected to generate a topic research prompt for document collections",
                max_length=60,
                null=True,
                verbose_name="Summarization AI Model used for generating research prompts to discover topics ",
            ),
        ),
        migrations.AddField(
            model_name="teamproject",
            name="summary_topic_model",
            field=models.CharField(
                choices=[
                    ("mixtral_7bx8", "Mixtral 7bx8 (Default)"),
                    ("mixtral_22bx8", "Mixtral 22bx8"),
                    ("llama3_70b", "Llama 3.1 70b"),
                ],
                help_text="This AI summarization model is used if selected to perform internal analysis on passages before drafting the final summary",
                max_length=60,
                null=True,
                verbose_name="Summarization AI Model used for topic analysis ",
            ),
        ),
        migrations.AlterField(
            model_name="teamproject",
            name="summary_model",
            field=models.CharField(
                choices=[
                    ("mixtral_7bx8", "Mixtral 7bx8 (Default)"),
                    ("mixtral_22bx8", "Mixtral 22bx8"),
                    ("llama3_70b", "Llama 3.1 70b"),
                ],
                default="mixtral_di_7bx8",
                help_text="An AI summarization model is a type of artificial intelligence that can automatically create a shorter version of a given text, while retaining its most important information. It uses natural language processing and understanding techniques to analyze the source text, identify key concepts, and generate a coherent and concise summary. This AI summarization model is used for all AI summarization requests in this project.",
                max_length=60,
                verbose_name="Summarization AI Model",
            ),
        ),
    ]
