# Generated by Django 5.0.7 on 2024-11-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_teamproject_summary_prompt_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamproject",
            name="summary_prompt_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mixtral_7bx8", "Mixtral 7bx8 (Default)"),
                    ("mixtral_22bx8", "Mixtral 22bx8"),
                    ("llama3_70b", "Llama 3.1 70b"),
                ],
                help_text="This AI summarization model is used if selected to generate a topic research prompt for document collections",
                max_length=60,
                null=True,
                verbose_name="Summarization AI Model used for generating research prompts to discover topics ",
            ),
        ),
        migrations.AlterField(
            model_name="teamproject",
            name="summary_topic_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mixtral_7bx8", "Mixtral 7bx8 (Default)"),
                    ("mixtral_22bx8", "Mixtral 22bx8"),
                    ("llama3_70b", "Llama 3.1 70b"),
                ],
                help_text="This AI summarization model is used if selected to perform internal analysis on passages before drafting the final summary",
                max_length=60,
                null=True,
                verbose_name="Summarization AI Model used for topic analysis ",
            ),
        ),
    ]
