# Generated by Django 5.0.7 on 2024-11-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="session_id",
            field=models.CharField(default=0, max_length=50, verbose_name="Session ID"),
            preserve_default=False,
        ),
    ]
