# Generated by Django 5.0.7 on 2024-11-21 01:52

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_formsubmission_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="nav_path",
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="Navigation Path"),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="page",
            field=app.utils.fields.DictionaryField(default=dict, verbose_name="Page Definition"),
        ),
    ]
