# Generated by Django 5.0.7 on 2024-11-28 06:12

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_formsubmission_nav_path_formsubmission_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextEmbedding",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                ("id", models.CharField(max_length=65, primary_key=True, serialize=False, unique=True)),
                ("text", models.TextField(verbose_name="Text")),
                ("embedding", app.utils.fields.ListField(default=list, verbose_name="Embedding")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
