# Generated by Django 5.0.7 on 2024-11-28 06:58

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_textembedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textembedding",
            name="embedding",
        ),
        migrations.AddField(
            model_name="textembedding",
            name="embeddings",
            field=app.utils.fields.ListField(default=list, verbose_name="Embeddings"),
        ),
    ]
